/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ydo4ki_memapi3_AccessorJniDirect */

#ifndef _Included_com_ydo4ki_memapi3_AccessorJniDirect
#define _Included_com_ydo4ki_memapi3_AccessorJniDirect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ydo4ki_memapi3_AccessorJniDirect
 * Method:    getByte
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_com_ydo4ki_memapi3_AccessorJniDirect_getByte
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ydo4ki_memapi3_AccessorJniDirect
 * Method:    putByte
 * Signature: (JB)V
 */
JNIEXPORT void JNICALL Java_com_ydo4ki_memapi3_AccessorJniDirect_putByte
  (JNIEnv *, jobject, jlong, jbyte);

/*
 * Class:     com_ydo4ki_memapi3_AccessorJniDirect
 * Method:    getShort
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_com_ydo4ki_memapi3_AccessorJniDirect_getShort
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ydo4ki_memapi3_AccessorJniDirect
 * Method:    getShortAligned
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_com_ydo4ki_memapi3_AccessorJniDirect_getShortAligned
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ydo4ki_memapi3_AccessorJniDirect
 * Method:    putShort
 * Signature: (JS)V
 */
JNIEXPORT void JNICALL Java_com_ydo4ki_memapi3_AccessorJniDirect_putShort
  (JNIEnv *, jobject, jlong, jshort);

/*
 * Class:     com_ydo4ki_memapi3_AccessorJniDirect
 * Method:    putShortAligned
 * Signature: (JS)V
 */
JNIEXPORT void JNICALL Java_com_ydo4ki_memapi3_AccessorJniDirect_putShortAligned
  (JNIEnv *, jobject, jlong, jshort);

/*
 * Class:     com_ydo4ki_memapi3_AccessorJniDirect
 * Method:    getInt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_ydo4ki_memapi3_AccessorJniDirect_getInt
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ydo4ki_memapi3_AccessorJniDirect
 * Method:    getIntAligned
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_ydo4ki_memapi3_AccessorJniDirect_getIntAligned
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ydo4ki_memapi3_AccessorJniDirect
 * Method:    putInt
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_ydo4ki_memapi3_AccessorJniDirect_putInt
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_ydo4ki_memapi3_AccessorJniDirect
 * Method:    putIntAligned
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_ydo4ki_memapi3_AccessorJniDirect_putIntAligned
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_ydo4ki_memapi3_AccessorJniDirect
 * Method:    getLong
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_ydo4ki_memapi3_AccessorJniDirect_getLong
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ydo4ki_memapi3_AccessorJniDirect
 * Method:    getLongAligned
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_ydo4ki_memapi3_AccessorJniDirect_getLongAligned
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ydo4ki_memapi3_AccessorJniDirect
 * Method:    putLong
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_ydo4ki_memapi3_AccessorJniDirect_putLong
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_ydo4ki_memapi3_AccessorJniDirect
 * Method:    putLongAligned
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_ydo4ki_memapi3_AccessorJniDirect_putLongAligned
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_ydo4ki_memapi3_AccessorJniDirect
 * Method:    getAddress
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_ydo4ki_memapi3_AccessorJniDirect_getAddress
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ydo4ki_memapi3_AccessorJniDirect
 * Method:    getAddressAligned
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_ydo4ki_memapi3_AccessorJniDirect_getAddressAligned
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ydo4ki_memapi3_AccessorJniDirect
 * Method:    putAddress
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_ydo4ki_memapi3_AccessorJniDirect_putAddress
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_ydo4ki_memapi3_AccessorJniDirect
 * Method:    putAddressAligned
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_ydo4ki_memapi3_AccessorJniDirect_putAddressAligned
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_ydo4ki_memapi3_AccessorJniDirect
 * Method:    copyMemory
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_ydo4ki_memapi3_AccessorJniDirect_copyMemory
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_ydo4ki_memapi3_AccessorJniDirect
 * Method:    moveMemory
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_ydo4ki_memapi3_AccessorJniDirect_moveMemory
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_ydo4ki_memapi3_AccessorJniDirect
 * Method:    compareMemory
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_com_ydo4ki_memapi3_AccessorJniDirect_compareMemory
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_ydo4ki_memapi3_AccessorJniDirect
 * Method:    setMemory
 * Signature: (JBJ)V
 */
JNIEXPORT void JNICALL Java_com_ydo4ki_memapi3_AccessorJniDirect_setMemory
  (JNIEnv *, jobject, jlong, jbyte, jlong);

/*
 * Class:     com_ydo4ki_memapi3_AccessorJniDirect
 * Method:    addressSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ydo4ki_memapi3_AccessorJniDirect_addressSize
  (JNIEnv *, jobject);

/*
 * Class:     com_ydo4ki_memapi3_AccessorJniDirect
 * Method:    deallocateMemory
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ydo4ki_memapi3_AccessorJniDirect_deallocateMemory
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ydo4ki_memapi3_AccessorJniDirect
 * Method:    allocateMemory0
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_ydo4ki_memapi3_AccessorJniDirect_allocateMemory0
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
